cargo-features = ["profile-rustflags"]

[package]
name = "sim"
version = "0.1.0"
keywords = ["game", "bevy"]
edition = "2021"
authors = ["Rratic"]
license = "MIT"

[features]
default = [
	# ref: https://docs.rs/bevy/latest/bevy/#cargo-features
	# Default Features
	"bevy/bevy_asset",
	"bevy/bevy_log",
	"bevy/bevy_picking",
	"bevy/bevy_render",
	"bevy/bevy_scene",
	"bevy/bevy_sprite",
	"bevy/bevy_state",
	"bevy/bevy_text",
	"bevy/bevy_ui",
	"bevy/bevy_window",
	"bevy/bevy_winit",
	"bevy/multi_threaded", # not known whether it's worth it
	"bevy/png",

	# Optional Features
	"bevy/dynamic_linking",
	"bevy/serialize",

	# Rapier
	"bevy_rapier2d/serde-serialize",

	# Bevy Common Assets
	"bevy_common_assets/toml",
]

devtools = ["default"]

[profile.dev]
debug = false
rustflags = ["-Z", "share-generics=off"]

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

[dependencies]
bevy = { version = "0.16", default-features = false }
bevy_common_assets = { version = "0.13", default-features = false }
bevy_rapier2d = "0.30.0"
serde = "1"
